import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Shopping App",
  description: "Shopping App generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
     
      <Navbar/>
      <div>
        <img className="m-auto" src="/cover.webp" alt="cover" />
      </div>
      <Footer/>
      
      </body>
    </html>
  );
}
